# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-09-05 22:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationtp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='parque',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='relationtp.Park'),
        ),
    ]
